# -----------------------------------------------------------
# PROFIL DE DEPLOIEMENT (RENDER / POSTGRESQL)
# -----------------------------------------------------------

# 1. Dialecte optimisé pour PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 2. Lien vers la base de données
# On utilise le nom exact de la variable que tu as créée sur Render
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 3. CRÉATION AUTOMATIQUE DES TABLES
# 'update' permet à Hibernate de créer les tables 'medicament' et 'fournisseur' s'il ne les trouve pas
spring.jpa.hibernate.ddl-auto=update

# 4. INITIALISATION DES DONNÉES (data.sql)
# 'always' force Spring à lire ton fichier data.sql pour remplir la base PostgreSQL
spring.sql.init.mode=always

# 5. Paramètres supplémentaires pour éviter les erreurs de driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true