# Profil de developpement, par defaut.
# On utilise le SGBD H2 en memoire vive
server.port=${PORT:8080}
spring.sql.init.encoding=UTF-8
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.web.resources.static-locations=classpath:/static/,file:/tmp

server.error.whitelabel.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.data.rest.defaultMediaType=application/json
spring.jackson.serialization.indent-output=true
spring.data.rest.base-path=api
server.forward-headers-strategy=native

server.error.include-stacktrace=never
logging.level.web=DEBUG
spring.mvc.log-request-details=true
logging.level.org.springframework=INFO
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=false
logging.level.org.hibernate.type=ERROR
logging.level.comptoirs=INFO
logging.pattern.console=%clr(%-5p)  %cyan(%logger{15}) - %msg %n

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# =======================================================
# CONFIGURATION POUR L'ENVOI DE MAILS (SENDGRID)
# =======================================================
# Remplace la valeur ci-dessous par la clé secrète copiée sur SendGrid (SG.xxxxx...)
sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.from-email=dahenedhouha@gmail.com